ARG zlib_version=latest
FROM zlib_debug:${zlib_version}

MAINTAINER Francis Duffy
LABEL Description="Build openssl."

ARG num_cores

COPY . /lib_src/openssl

RUN apt-get update \
  && apt-get upgrade -y \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y perl \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* \
  && cd /lib_src/openssl \
  && find -regex ".*\.\(sh\|in\|ac\|am\)" -exec dos2unix {} ';' \
  && dos2unix config \
  && ./config --debug \
  && make -j ${num_cores} \
  && make install_sw \
  && cd / \
  && ldconfig

CMD bash
